# Generated by Django 3.2.5 on 2022-01-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('P', 'Product'), ('Y', 'Payment'), ('C', 'Contract'), ('B', 'Bidding'), ('N', 'Negotiation'), ('M', 'Commission'), ('U', 'User'), ('O', 'Other')], default='O', max_length=50, verbose_name='Related to')),
                ('ntype', models.CharField(choices=[('I', 'Info'), ('S', 'Success'), ('W', 'Warning'), ('E', 'Error')], default='I', max_length=50, verbose_name='Type')),
                ('link', models.CharField(default='#', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('pdate', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Self_noti_user', to=settings.AUTH_USER_MODEL, verbose_name='For User')),
            ],
        ),
    ]
