# Generated by Django 3.2.5 on 2022-10-17 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('P', 'mdi-gift'), ('J', 'mdi-briefcase'), ('I', 'mdi-email'), ('R', 'mdi-note-text'), ('L', 'mdi-poll'), ('U', 'mdi-account'), ('O', 'mdi-bell')], default='O', max_length=50, verbose_name='Related to'),
        ),
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('bank_account', 'Bank Account'), ('vpa', 'UPI Address')], max_length=12, null=True, verbose_name='Account Type')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Name')),
                ('upi', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI Address')),
                ('accountno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account No')),
                ('ifsc', models.CharField(blank=True, max_length=11, null=True, verbose_name='IFSC Code')),
                ('contact_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact ID')),
                ('fund_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fund Account ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date Edited')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='Fund Account of User')),
            ],
            options={
                'verbose_name_plural': 'Fund Accounts',
            },
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Order ID')),
                ('amount', models.IntegerField(default=False, verbose_name='Bounty Earned')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Earned')),
                ('paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('requested', models.BooleanField(default=False, verbose_name='Requested')),
                ('reqdate', models.DateTimeField(blank=True, null=True, verbose_name='Date Requested')),
                ('claimed', models.BooleanField(default=False, verbose_name='Claimed')),
                ('cldate', models.DateTimeField(blank=True, null=True, verbose_name='Date Claimed')),
                ('fro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_from_company', to=settings.AUTH_USER_MODEL, verbose_name='From Company')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_of_report', to='main.report', verbose_name='Of Report')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_to_user', to=settings.AUTH_USER_MODEL, verbose_name='To User')),
            ],
            options={
                'verbose_name_plural': 'Bounties',
            },
        ),
    ]
