# Generated by Django 3.2.5 on 2022-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(default=18408585, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
