# Generated by Django 3.2.5 on 2022-10-18 19:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.IntegerField(default=main.models.random_report_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
