# Generated by Django 3.2.5 on 2022-10-17 11:23

import back.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('bio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bio/Slogan')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Company Staff Permissions')),
                ('is_company', models.BooleanField(default=False, verbose_name='Company Permissions')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin Permissions')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super Admin Permissions')),
                ('type', models.CharField(choices=[('S', 'Super Admin'), ('A', 'Admin'), ('C', 'Company'), ('Ct', 'Company Staff'), ('U', 'User')], default='U', max_length=12, verbose_name='Account Type')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles', verbose_name='Profile Photo')),
                ('contact', models.CharField(blank=True, max_length=12, null=True, verbose_name='Contact Info')),
                ('companytype', models.CharField(blank=True, choices=[('S', 'Start-Up'), ('E', 'Enterprise'), ('M', 'Managed')], max_length=30, null=True, verbose_name='Company Type')),
                ('refreputation', models.IntegerField(default=0, verbose_name='Referral Code Reputation')),
                ('upvotereputation', models.IntegerField(default=0, verbose_name='Upvotes Reputation')),
                ('likesreputation', models.IntegerField(default=0, verbose_name='Likes Reputation')),
                ('verificationreputation', models.IntegerField(default=0, verbose_name='Verification Reputation')),
                ('otherreputation', models.IntegerField(default=0, verbose_name='Main Reputation')),
                ('totalreputation', models.IntegerField(default=0, verbose_name='Total Reputation')),
                ('refcode', models.CharField(default=back.models.random_string, max_length=6, verbose_name='Referral Code')),
                ('visits', models.IntegerField(default=0, verbose_name='Profile Visits')),
                ('reset', models.DateTimeField(blank=True, null=True, verbose_name='Previous Reset Time')),
                ('website', models.URLField(blank=True, max_length=60, null=True, verbose_name='Website URL')),
                ('github', models.URLField(blank=True, null=True, verbose_name='Github Link')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
                ('likes', models.ManyToManyField(blank=True, related_name='_back_user_likes_+', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('refuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Attached To')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
