# Generated by Django 3.2.5 on 2022-10-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companytype',
            field=models.CharField(blank=True, choices=[('S', 'Start-Up'), ('E', 'Enterprise'), ('M', 'Managed')], max_length=100, null=True, verbose_name='Company Type'),
        ),
    ]
