# Generated by Django 3.2.16 on 2025-04-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_user_companytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
