"""
Django settings for honeb project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p3%phmthoys#bb6yw)hfkk%bpe@!!^!w_v(rz0uptj)x-^w%d*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True   

ALLOWED_HOSTS = ['.cyber3ra.com','localhost','127.0.0.1','127.0.1.1','.cyber3ra-backend-main.azurewebsites.net',"*"]

APP_PROD = False
APP_DOMAIN = 'https://cyber3ra-backend-main.azurewebsites.net' if APP_PROD else 'http://localhost:8060'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # 'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'back',
    'main',
    'other',
    'corsheaders',
    'ctf'   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'honeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'back.context.chart_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'honeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DEV
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hone',
#         'USER': 'postgres',
#         'PASSWORD': 'EngineeringHR',
#         'HOST' : 'localhost'
#     }
# }   

# PROD
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cyberdata',
#         'USER': 'admin',
#         'PASSWORD': 'EngineeringHR',
#         'HOST' : 'cyberdata.cp94iuvyxkox.ap-south-1.rds.amazonaws.com',
#         'PORT' : '3306'
#     }
# }   

# DATABASE PROD 1

# DATABASES = {
#         'default': {
#             'ENGINE': 'mssql',
#             'NAME': 'cyber3ra',
#             'USER': 'adarsh',
#             'PASSWORD': 'Cyber3ra@nagpur',
#             'HOST': 'cyber3ra-backstage.database.windows.net',
#             'PORT': '1433',
#             'OPTIONS': {
#                 'driver': 'ODBC Driver 18 for SQL Server',
#             },
#         },
#     } if APP_PROD else {
#     'default':{
#         'ENGINE':'django.db.backends.sqlite3',
#         'NAME':BASE_DIR/'db.sqlite3',
#     }
    
# }

# DATABASE PROD 2



DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'cyber3ra-main',
            'USER': 'adarsh',
            'PASSWORD': 'Cyber3ra@nagpur',
            'HOST': 'cyber3ra-db.mysql.database.azure.com',
            'PORT': '',
            # 'SSL_CA': True
            # 'SSL_DISABLED': False
            'OPTIONS': {
                'ssl': {'ca':  BASE_DIR/'BaltimoreCyberTrustRoot.crt.pem' }
            }
            # 'OPTIONS': {
            #     'driver': 'ODBC Driver 18 for SQL Server',
            # },
        },
    } if APP_PROD else {
    'default':{
        'ENGINE':'django.db.backends.sqlite3',
        'NAME':BASE_DIR/'db.sqlite3',
    }
    
}


# DATABASES =


# PROD
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'cyber3ra',
#         'USER': 'adarsh',
#         'PASSWORD': 'Cyber3ra@nagpur',
#         'HOST' : 'cyber3ra-backstage.database.windows.net',
#         'PORT' : ''
#     }
# }   

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE =  'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATIC_URL = '/static/'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3500",
    'http://127.0.0.1:3500',
    # "http://localhost:3005",
    # 'http://127.0.0.1:3005',
    # 'http://127.0.0.1:53622',
    'https://cyfront.vercel.app',
    'http://192.168.0.225:3500'
    # 'http://cyber3ra.com',
]

# USE_TZ = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'nikhilrai662@gmail.com'
EMAIL_HOST_PASSWORD = 'mnkr wvoa drfo rauv'

EMAIL_HOST_NAME = 'Cyber3ra <'+EMAIL_HOST_USER+'>'
# EMAIL_HOST_NAME = 'no-reply@cyber3ra.com'


SECURE_BROWSER_XSS_FILTER = True

SECURE_SSL_REDIRECT = False

DEFAULT_AUTO_FIELD='django.db.models.AutoField'

AUTH_USER_MODEL = 'back.User'

TOKEN_MODEL = 'rest_framework.authtoken.Token'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=86400),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=180),
    'UPDATE_LAST_LOGIN': True,
}

REST_FRAMEWORK = {
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.SessionAuthentication',
    #     'rest_framework.authentication.TokenAuthentication',
    # ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.TokenAuthentication',
        
    # ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'COERCE_DECIMAL_TO_STRING': False
}


AUTHENTICATION_BACKENDS = ['back.backends.AuthCustom',]


PASSWORD_RESET_TIMEOUT = 14400






DJANGO_SUPERUSER_CODE = '1536489'




# RAZOR_KEY_ID = 'rzp_live_EFhmlMTheevuyc'
# RAZOR_KEY_SECRET = 'xqJZSv1pzB2IM5I862aD02fJ'

RAZOR_KEY_ID = 'rzp_live_aeeiG5xkLFDMJO'
RAZOR_KEY_SECRET = 'Kb11mEVtedGs904aczwNlr2Y'





TEST_RAZOR_KEY_ID = 'rzp_live_aeeiG5xkLFDMJO' if APP_PROD else 'rzp_test_BhGFPgvJ5z7twL'
TEST_RAZOR_KEY_SECRET = 'Kb11mEVtedGs904aczwNlr2Y' if APP_PROD else '0YboDODgszMcJDwVRV8xUbZT'


# SITE_ID = 1



# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'filters': {
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse'
#         }
#     },
#     'handlers': {
#         'logfile': {
#             'class': 'logging.handlers.WatchedFileHandler',
#             'filename': 'D:\home\site\wwwroot\myapp.log'
#         }
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['logfile'],
#             'level': 'ERROR',
#             'propagate': False,
#         }
#     }
#  }